// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
using System;
using System.Threading;
using System.Threading.Tasks;
using Facility.Core;
using Facility.Core.Http;

namespace Faithlife.SurveyApi.v1.Client.Http
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class HttpClientSurveyApi : HttpClientService, ISurveyApi
	{
		/// <summary>
		/// Creates the service.
		/// </summary>
		public HttpClientSurveyApi(HttpClientServiceSettings settings = null)
			: base(settings, defaultBaseUri: null)
		{
		}

		/// <summary>
		/// Create a survey
		/// </summary>
		public Task<ServiceResult<CreateSurveyResponseDto>> CreateSurveyAsync(CreateSurveyRequestDto request, CancellationToken cancellationToken) =>
			TrySendRequestAsync(SurveyApiHttpMapping.CreateSurveyMapping, request, cancellationToken);

		/// <summary>
		/// Submit a response to a survey
		/// </summary>
		public Task<ServiceResult<SubmitSurveyResponseResponseDto>> SubmitSurveyResponseAsync(SubmitSurveyResponseRequestDto request, CancellationToken cancellationToken) =>
			TrySendRequestAsync(SurveyApiHttpMapping.SubmitSurveyResponseMapping, request, cancellationToken);
	}
}
