// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net;
using System.Net.Http;
using Facility.Core;
using Facility.Core.Http;
using Newtonsoft.Json.Linq;

#pragma warning disable 612, 618 // member is obsolete

namespace Faithlife.SurveyApi.v1.Client.Http
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public static partial class SurveyApiHttpMapping
	{
		/// <summary>
		/// Create a survey
		/// </summary>
		public static readonly HttpMethodMapping<CreateSurveyRequestDto, CreateSurveyResponseDto> CreateSurveyMapping =
			new HttpMethodMapping<CreateSurveyRequestDto, CreateSurveyResponseDto>.Builder
			{
				HttpMethod = HttpMethod.Post,
				Path = "/surveys",
				RequestBodyType = typeof(CreateSurveyRequestDto),
				ResponseMappings =
				{
					new HttpResponseMapping<CreateSurveyResponseDto>.Builder
					{
						StatusCode = (HttpStatusCode) 200,
						ResponseBodyType = typeof(CreateSurveyResponseDto),
					}.Build(),
				},
			}.Build();

		/// <summary>
		/// Submit a response to a survey
		/// </summary>
		public static readonly HttpMethodMapping<SubmitSurveyResponseRequestDto, SubmitSurveyResponseResponseDto> SubmitSurveyResponseMapping =
			new HttpMethodMapping<SubmitSurveyResponseRequestDto, SubmitSurveyResponseResponseDto>.Builder
			{
				HttpMethod = HttpMethod.Post,
				Path = "/surveys/response",
				RequestBodyType = typeof(SubmitSurveyResponseRequestDto),
				ResponseMappings =
				{
					new HttpResponseMapping<SubmitSurveyResponseResponseDto>.Builder
					{
						StatusCode = (HttpStatusCode) 200,
						ResponseBodyType = typeof(SubmitSurveyResponseResponseDto),
					}.Build(),
				},
			}.Build();
	}
}
