// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
using System;
using System.Threading;
using System.Threading.Tasks;
using Facility.Core;

namespace Faithlife.SurveyApi.v1.Client
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public partial interface ISurveyApi
	{
		/// <summary>
		/// Create a survey
		/// </summary>
		Task<ServiceResult<CreateSurveyResponseDto>> CreateSurveyAsync(CreateSurveyRequestDto request, CancellationToken cancellationToken);

		/// <summary>
		/// Submit a response to a survey
		/// </summary>
		Task<ServiceResult<SubmitSurveyResponseResponseDto>> SubmitSurveyResponseAsync(SubmitSurveyResponseRequestDto request, CancellationToken cancellationToken);
	}
}
