// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Faithlife.SurveyApi.v1.Client
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class QuestionDto : ServiceDto<QuestionDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public QuestionDto()
		{
		}

		public string Id { get; set; }

		public string Prompt { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(QuestionDto other)
		{
			return other != null &&
				Id == other.Id &&
				Prompt == other.Prompt;
		}
	}
}
