// <auto-generated>
// DO NOT EDIT: generated by fsdgencsharp
// </auto-generated>
using System;
using System.Collections.Generic;
using Facility.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Faithlife.SurveyApi.v1.Client
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgencsharp", "")]
	public sealed partial class SurveyResponseDto : ServiceDto<SurveyResponseDto>
	{
		/// <summary>
		/// Creates an instance.
		/// </summary>
		public SurveyResponseDto()
		{
		}

		public string SurveyResponseId { get; set; }

		public string SurveyId { get; set; }

		public string CustomerName { get; set; }

		public string CustomerEmail { get; set; }

		public IReadOnlyList<QuestionResponseDto> QuestionResponses { get; set; }

		/// <summary>
		/// Determines if two DTOs are equivalent.
		/// </summary>
		public override bool IsEquivalentTo(SurveyResponseDto other)
		{
			return other != null &&
				SurveyResponseId == other.SurveyResponseId &&
				SurveyId == other.SurveyId &&
				CustomerName == other.CustomerName &&
				CustomerEmail == other.CustomerEmail &&
				ServiceDataUtility.AreEquivalentFieldValues(QuestionResponses, other.QuestionResponses);
		}
	}
}
