// DO NOT EDIT: generated by fsdgenaspnet
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Facility.Core;
using Faithlife.SurveyApi.v1.Client;
using Microsoft.AspNetCore.Mvc;

#pragma warning disable 1591 // missing XML comment

namespace SurveyApi.v1.Controllers
{
	[System.CodeDom.Compiler.GeneratedCode("fsdgenaspnet", "")]
	public partial class SurveyApiController
	{
		[HttpPost, Route("surveys")]
		public Task<HttpResponseMessage> CreateSurvey(HttpRequestMessage httpRequest, CancellationToken cancellationToken = default(CancellationToken))
		{
			return GetServiceHttpHandler().TryHandleCreateSurveyAsync(httpRequest, cancellationToken);
		}

		[HttpPost, Route("surveys/response")]
		public Task<HttpResponseMessage> SubmitSurveyResponse(HttpRequestMessage httpRequest, CancellationToken cancellationToken = default(CancellationToken))
		{
			return GetServiceHttpHandler().TryHandleSubmitSurveyResponseAsync(httpRequest, cancellationToken);
		}
	}
}
